import { all } from 'redux-saga/effects';
import {
  watchForChangePassword,
  watchForChangeUserData,
  watchForLoginUser,
  watchForLogoutUser,
  watchForGetUserList,
} from './user';
import {
  watchForCreateCustomer,
  watchForDeleteCustomer,
  watchForDeleteCustomerAddress,
  watchForDeleteCustomerPhone,
  watchForGetCustomer,
  watchForGetCustomerList,
  watchForGetCustomerListPage,
  watchForSaveCustomer,
  watchForSaveCustomerAddress,
  watchForSaveCustomerPhone,
} from './customer';
import {
  watchForCreateNote,
  watchForDeleteNote,
  watchForGetNoteList,
  watchForSaveNote,
} from './note';
import { watchForGetFramework, watchForSaveFramework } from './framework';
import {
  watchForDeleteCharge,
  watchForDeleteSupplier,
  watchForGetBrands,
  watchForGetCoreData,
  watchForSaveBrands,
  watchForSaveCharge,
  watchForSaveSupplier,
} from './core';
import {
  watchForAddBikePart,
  watchForGetBike,
  watchForGetBikeParts,
  watchForArchiveFrames,
  watchForDeleteBikePart,
  watchForDeleteBikes,
  watchForDeleteFrames,
  watchForGetFrames,
  watchForSaveBike,
  watchForSaveBikePart,
  watchForSaveFrame,
  watchForUploadFrame,
} from './bike';
import {
  watchForDeletePart,
  watchForDeleteSupplierProduct,
  watchForGetParts,
  watchForSavePart,
  watchForSavePartsAndSupplierProducts,
  watchForSaveSupplierProduct,
  watchForUploadParts,
} from './part';
import {
  watchForCopyQuote,
  watchForCreateQuote,
  watchForGetQuote,
  watchForGetQuoteList,
  watchForArchiveQuote,
  watchForSaveQuote,
  watchForUnarchiveQuote,
  watchForSaveQuotePart,
  watchForDeleteQuotePart,
  watchForGetQuoteToCopy,
  watchForIssueQuote,
} from './quote';
import { watchForChangeRoute } from './application';

export default function* rootSaga() {
  yield all([
    watchForChangeRoute(),
    watchForLoginUser(),
    watchForLogoutUser(),
    watchForChangePassword(),
    watchForChangeUserData(),
    watchForGetUserList(),
    watchForGetFramework(),
    watchForSaveFramework(),
    watchForGetCustomerList(),
    watchForGetCustomerListPage(),
    watchForGetCustomer(),
    watchForCreateCustomer(),
    watchForDeleteCustomer(),
    watchForSaveCustomer(),
    watchForDeleteCustomerAddress(),
    watchForSaveCustomerAddress(),
    watchForDeleteCustomerPhone(),
    watchForSaveCustomerPhone(),
    watchForCreateNote(),
    watchForDeleteNote(),
    watchForSaveNote(),
    watchForGetNoteList(),
    watchForGetCoreData(),
    watchForGetBrands(),
    watchForSaveBrands(),
    watchForSaveSupplier(),
    watchForDeleteSupplier(),
    watchForArchiveFrames(),
    watchForSaveFrame(),
    watchForUploadFrame(),
    watchForGetFrames(),
    watchForDeleteFrames(),
    watchForDeleteBikes(),
    watchForSaveBike(),
    watchForSaveBikePart(),
    watchForDeleteBikePart(),
    watchForGetBike(),
    watchForGetBikeParts(),
    watchForAddBikePart(),
    watchForSavePart(),
    watchForDeletePart(),
    watchForUploadParts(),
    watchForGetParts(),
    watchForCreateQuote(),
    watchForCopyQuote(),
    watchForGetQuoteList(),
    watchForGetQuote(),
    watchForSaveQuote(),
    watchForUnarchiveQuote(),
    watchForArchiveQuote(),
    watchForSaveQuotePart(),
    watchForDeleteQuotePart(),
    watchForGetQuoteToCopy(),
    watchForIssueQuote(),
    watchForSaveSupplierProduct(),
    watchForDeleteSupplierProduct(),
    watchForSavePartsAndSupplierProducts(),
    watchForSaveCharge(),
    watchForDeleteCharge(),
  ]);
}
